# Generated by Django 3.0.6 on 2020-05-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200530_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emplId', models.PositiveIntegerField()),
                ('hours', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
