# Generated by Django 3.0.6 on 2020-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200530_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emplId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
