# Generated by Django 3.0.6 on 2020-05-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytimecard',
            name='payCheck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.PayCheck'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='total',
            field=models.FloatField(blank=True),
        ),
    ]
