# Generated by Django 3.0.6 on 2020-05-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200530_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimecard',
            name='emplId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Employee'),
        ),
    ]
