# Generated by Django 3.0.6 on 2020-05-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20200530_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='emplId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Employee'),
        ),
    ]
