# Generated by Django 3.0.6 on 2020-05-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_paycheck_emplid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployementRecod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True)),
                ('emplId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Employee')),
            ],
        ),
    ]
