# Generated by Django 3.0.6 on 2020-05-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_employementrecod'),
    ]

    operations = [
        migrations.AddField(
            model_name='employementrecod',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='business.EmployementRecod'),
        ),
        migrations.AddField(
            model_name='employementrecod',
            name='position',
            field=models.CharField(choices=[('M', 'Manager'), ('E', 'Base Employee')], default='Base Employee', max_length=25),
        ),
        migrations.AddField(
            model_name='employementrecod',
            name='role',
            field=models.CharField(default='unassigned', max_length=100),
        ),
    ]
