# Generated by Django 3.0.6 on 2020-05-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20200530_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(blank=True)),
                ('tax', models.FloatField()),
                ('tip', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('payment', models.CharField(choices=[('Crd', 'Card'), ('Csh', 'Cash')], max_length=25)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Employee')),
            ],
        ),
    ]
