# Generated by Django 3.0.6 on 2020-05-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.Location'),
        ),
    ]
