# Generated by Django 3.0.6 on 2020-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_receipt_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('joinDate', models.DateField()),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
