# Generated by Django 3.0.6 on 2020-05-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20200530_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField()),
                ('menuItem', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('Receipt', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.Receipt')),
            ],
        ),
    ]
