# Generated by Django 3.0.6 on 2020-05-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_lineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='Receipt',
            new_name='receipt',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField()),
                ('returnDate', models.DateField()),
                ('qty', models.IntegerField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Employee')),
                ('receiptItem', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.LineItem')),
            ],
        ),
    ]
