# Generated by Django 3.0.6 on 2020-05-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20200530_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='refund',
            name='ordinal',
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='menuItem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.MenuItem'),
        ),
    ]
