# Generated by Django 3.0.6 on 2020-05-30 21:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20200530_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('amount', models.FloatField()),
                ('expenseName', models.CharField(max_length=200)),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.Location')),
            ],
        ),
    ]
