# Generated by Django 3.0.6 on 2020-05-30 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20200530_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.Location')),
                ('supplierId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.Location')),
                ('stockItem', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='business.StockItem')),
            ],
        ),
    ]
