# Generated by Django 3.0.6 on 2020-06-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20200530_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployementRecod',
            new_name='EmploymentRecord',
        ),
    ]
